---
abstract: 'L<App::Nopaste> interface to L<http://p.linode.com>'
author:
  - 'Ævar Arnfjörð Bjarmason <avar@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Nopaste-Service-Linode
requires:
  App::Nopaste: 0.19
  App::Nopaste::Service::AnyPastebin: 0.01
resources:
  Ratings: http://cpanratings.perl.org/d/App-Nopaste-Service-Linode
  bugtracker: http://github.com/avar/app-nopaste-service-linode/issues
  homepage: http://search.cpan.org/dist/App-Nopaste-Service-Linode/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/avar/app-nopaste-service-linode
version: 0.02
